[pytest]
pythonpath = . tests
testpaths = tests
python_files = test_*.py
addopts = -v --tb=short --strict-markers
timeout = 300

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    smoke: Quick critical checks
    acceptance: Full scenarios
    ui: Browser tests Playwright
    api: Backend and endpoint verific.
